"""empty message

Revision ID: 1082a9510869
Revises: a8665336cfa1
Create Date: 2020-01-24 08:23:44.315789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1082a9510869'
down_revision = 'a8665336cfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'activity_group',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('student', 'admission_year',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('student', 'fname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('student', 'gender',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('student', 'level',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('student', 'p_mobile1',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('student', 'p_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('student', 'parent_id',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('student', 's_class',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('student', 's_type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('student', 'school',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('student', 'sname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_index('p_email', table_name='student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('p_email', 'student', ['p_email'], unique=True)
    op.alter_column('student', 'sname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('student', 'school',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('student', 's_type',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('student', 's_class',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('student', 'parent_id',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 'p_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('student', 'p_mobile1',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 'level',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 'gender',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('student', 'fname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('student', 'admission_year',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('student', 'activity_group',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
