"""empty message

Revision ID: 1165e453879a
Revises: 3604136c36e1
Create Date: 2020-01-23 01:28:55.369261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1165e453879a'
down_revision = '3604136c36e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'amount')
    # ### end Alembic commands ###
