"""many tables added

Revision ID: 1791f99f3b21
Revises: 66a25b7e0f19
Create Date: 2020-01-22 09:05:41.478628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1791f99f3b21'
down_revision = '66a25b7e0f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('student_backup')
    op.drop_table('parent')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('billing_details')
    op.add_column('academic_calendar', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('academic_calendar', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('academic_calendar', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'academic_calendar', ['description'])
    op.drop_column('academic_calendar', 'academic_calendar_id')
    op.drop_column('academic_calendar', 'Description')
    op.drop_column('academic_calendar', 'Start_date')
    op.add_column('billing', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'billing', 'academic_calendar', ['academic_calendar_id'], ['id'])
    op.create_foreign_key(None, 'billing', 'student_category', ['student_category_id'], ['id'])
    op.drop_column('billing', 'amount')
    op.add_column('fee_category', sa.Column('id', sa.Integer(), nullable=False, auto_increment=True))
    op.drop_column('fee_category', 'fee_category_id')
    op.add_column('fee_schedule', sa.Column('id', sa.Integer(), nullable=False, auto_increment=True))
    op.add_column('fee_schedule', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('fee_schedule', sa.Column('is_percent', sa.Boolean(), nullable=True))
    op.drop_column('fee_schedule', 'is_percentage')
    op.drop_column('fee_schedule', 'is_active')
    op.drop_column('fee_schedule', 'fee_schedule_id')
    op.add_column('fee_schedule_detail', sa.Column('id', sa.Integer(), nullable=False, auto_increment=True))
    op.add_column('fee_schedule_detail', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('fee_schedule_detail', sa.Column('update_user', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'fee_schedule_detail', 'fee_schedule', ['fee_schedule_id'], ['id'])
    op.drop_column('fee_schedule_detail', 'student_category_id')
    op.drop_column('fee_schedule_detail', 'fsd_id')
    op.add_column('receipt', sa.Column('insert_date', sa.DateTime(), nullable=True))
    op.add_column('receipt', sa.Column('insert_user', sa.String(length=16), nullable=True))
    op.add_column('receipt', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('receipt', sa.Column('tran_date', sa.DateTime(), nullable=True))
    op.add_column('receipt', sa.Column('tran_desc', sa.String(length=128), nullable=True))
    op.add_column('receipt', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('receipt', sa.Column('update_user', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'receipt', 'receipt_source', ['receipt_source_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'student', ['student_id'], ['student_id'])
    op.drop_column('receipt', 'updateuser')
    op.drop_column('receipt', 'updatedate')
    op.drop_column('receipt', 'academic_calendar_id')
    op.drop_column('receipt', 'insertdate')
    op.drop_column('receipt', 'trandesc')
    op.drop_column('receipt', 'trandate')
    op.drop_column('receipt', 'insertuser')
    op.add_column('receipt_source', sa.Column('id', sa.Integer(), nullable=False, auto_increment=True))
    op.create_unique_constraint(None, 'receipt_source', ['source'])
    op.drop_column('receipt_source', 'receipt_source_id')
    op.add_column('student', sa.Column('p_mobile1', sa.String(length=16), nullable=True))
    op.add_column('student', sa.Column('student_id', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=False)
    op.create_unique_constraint(None, 'student', ['p_email'])
    op.create_foreign_key(None, 'student', 'billing', ['billing_id'], ['billing_id'])
    op.drop_column('student', 'school')
    op.drop_column('student', 'class')
    op.drop_column('student', 'p_mobile')
    op.drop_column('student', 'Student_id')
    op.add_column('student_category', sa.Column('id', sa.Integer(), nullable=False, auto_increment=True))
    op.create_unique_constraint(None, 'student_category', ['description'])
    op.drop_column('student_category', 'student_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_category', sa.Column('student_category_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'student_category', type_='unique')
    op.drop_column('student_category', 'id')
    op.add_column('student', sa.Column('Student_id', mysql.VARCHAR(length=16), nullable=False))
    op.add_column('student', sa.Column('p_mobile', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('student', sa.Column('class', mysql.VARCHAR(length=3), nullable=True))
    op.add_column('student', sa.Column('school', mysql.CHAR(length=3), nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_column('student', 'student_id')
    op.drop_column('student', 'p_mobile1')
    op.add_column('receipt_source', sa.Column('receipt_source_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'receipt_source', type_='unique')
    op.drop_column('receipt_source', 'id')
    op.add_column('receipt', sa.Column('insertuser', mysql.VARCHAR(length=16), nullable=True))
    op.add_column('receipt', sa.Column('trandate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('receipt', sa.Column('trandesc', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('receipt', sa.Column('insertdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('receipt', sa.Column('academic_calendar_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('receipt', sa.Column('updatedate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('receipt', sa.Column('updateuser', mysql.VARCHAR(length=16), nullable=True))
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'update_user')
    op.drop_column('receipt', 'update_date')
    op.drop_column('receipt', 'tran_desc')
    op.drop_column('receipt', 'tran_date')
    op.drop_column('receipt', 'is_current')
    op.drop_column('receipt', 'insert_user')
    op.drop_column('receipt', 'insert_date')
    op.add_column('fee_schedule_detail', sa.Column('fsd_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('fee_schedule_detail', sa.Column('student_category_id', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fee_schedule_detail', type_='foreignkey')
    op.drop_column('fee_schedule_detail', 'update_user')
    op.drop_column('fee_schedule_detail', 'update_date')
    op.drop_column('fee_schedule_detail', 'id')
    op.add_column('fee_schedule', sa.Column('fee_schedule_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('fee_schedule', sa.Column('is_active', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('fee_schedule', sa.Column('is_percentage', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.drop_column('fee_schedule', 'is_percent')
    op.drop_column('fee_schedule', 'is_current')
    op.drop_column('fee_schedule', 'id')
    op.add_column('fee_category', sa.Column('fee_category_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('fee_category', 'id')
    op.add_column('billing', sa.Column('amount', mysql.DECIMAL(precision=19, scale=9), nullable=True))
    op.drop_constraint(None, 'billing', type_='foreignkey')
    op.drop_constraint(None, 'billing', type_='foreignkey')
    op.drop_column('billing', 'id')
    op.add_column('academic_calendar', sa.Column('Start_date', sa.DATE(), nullable=True))
    op.add_column('academic_calendar', sa.Column('Description', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('academic_calendar', sa.Column('academic_calendar_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'academic_calendar', type_='unique')
    op.drop_column('academic_calendar', 'start_date')
    op.drop_column('academic_calendar', 'id')
    op.drop_column('academic_calendar', 'description')
    op.create_table('billing_details',
    sa.Column('student_bill_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('fee_schedule_id', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=19, scale=9), server_default=sa.text("'0.000000000'"), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('is_current', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('insert_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`is_admin` in (0,1))', name='users_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('parent',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('mobile1', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('mobile2', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('insertuser', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insertdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updateuser', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('updatedate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('parent_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_backup',
    sa.Column('Student_id', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('sname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('oname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True),
    sa.Column('s_type', mysql.CHAR(length=2), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('school', mysql.CHAR(length=3), nullable=True),
    sa.Column('class', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('activity_group', mysql.CHAR(length=1), nullable=True),
    sa.Column('admission_year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('parent_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('p_address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('p_pno', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('p_mobile', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_mobile2', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_mobile3', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_fresher', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_stopped', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_staff', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('billing_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
