"""empty message

Revision ID: 190725c3a381
Revises: ecac02e05b22
Create Date: 2020-01-24 02:19:16.174310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190725c3a381'
down_revision = 'ecac02e05b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_class', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('school', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'school')
    op.drop_column('student', 's_class')
    # ### end Alembic commands ###
