"""This is ok

Revision ID: 3604136c36e1
Revises: 8e7ac3595dfb
Create Date: 2020-01-23 01:13:16.014119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3604136c36e1'
down_revision = '8e7ac3595dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('receipt', 'is_current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('receipt', 'is_active')
    # ### end Alembic commands ###
