"""user table created

Revision ID: 66a25b7e0f19
Revises: 
Create Date: 2020-01-22 07:13:45.810736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66a25b7e0f19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('fee_schedule_detail')
    op.drop_table('receipt_source')
    op.drop_table('student')
    op.drop_table('receipt')
    op.drop_table('student_category')
    op.drop_table('billing')
    op.drop_table('billing_details')
    op.drop_table('fee_category')
    op.drop_table('fee_schedule')
    op.drop_table('academic_calendar')
    op.drop_table('student_backup')
    op.drop_table('parent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('mobile1', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('mobile2', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('insertuser', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insertdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updateuser', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('updatedate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('parent_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_backup',
    sa.Column('Student_id', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('sname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('oname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True),
    sa.Column('s_type', mysql.CHAR(length=2), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('school', mysql.CHAR(length=3), nullable=True),
    sa.Column('class', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('activity_group', mysql.CHAR(length=1), nullable=True),
    sa.Column('admission_year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('parent_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('p_address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('p_pno', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('p_mobile', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_mobile2', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_mobile3', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_fresher', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_stopped', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_staff', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('billing_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('academic_calendar',
    sa.Column('academic_calendar_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Description', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('Start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('academic_year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('is_current', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('academic_calendar_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fee_schedule',
    sa.Column('fee_schedule_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=19, scale=9), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_percentage', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fee_schedule_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fee_category',
    sa.Column('fee_category_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('fee_category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('billing_details',
    sa.Column('student_bill_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('fee_schedule_id', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=19, scale=9), server_default=sa.text("'0.000000000'"), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('is_current', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('billing',
    sa.Column('billing_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('academic_calendar_id', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=19, scale=9), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_current', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('billing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_category',
    sa.Column('student_category_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('student_category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('receipt',
    sa.Column('receipt_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('trandesc', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=19, scale=9), nullable=True),
    sa.Column('currency', mysql.CHAR(length=3), server_default=sa.text("'GHS'"), nullable=True),
    sa.Column('trandate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('insertuser', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insertdate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updateuser', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('updatedate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('receipt_source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('academic_calendar_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('receipt_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('Student_id', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('sname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('oname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True),
    sa.Column('s_type', mysql.CHAR(length=2), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('school', mysql.CHAR(length=3), nullable=True),
    sa.Column('class', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('activity_group', mysql.CHAR(length=1), nullable=True),
    sa.Column('admission_year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('parent_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('p_address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('p_pno', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('p_mobile', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_mobile2', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('p_mobile3', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_user', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('update_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_fresher', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_stopped', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_staff', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('billing_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('receipt_source',
    sa.Column('receipt_source_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('source', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('receipt_source_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fee_schedule_detail',
    sa.Column('fsd_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fee_schedule_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_fresher', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('is_staff', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('school', mysql.CHAR(length=3), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=19, scale=0), server_default=sa.text("'0'"), nullable=True),
    sa.Column('insert_user', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('insert_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_current', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('student_category_id', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fsd_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
