"""empty message

Revision ID: 8cb792d0c2da
Revises: aeef088e8ec6
Create Date: 2020-01-24 00:27:22.543151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cb792d0c2da'
down_revision = 'aeef088e8ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('billing', 'insert_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('billing', 'update_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('receipt', 'amount',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('receipt', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('receipt', 'insert_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('receipt', 'tran_desc',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('receipt', 'update_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 'activity_group',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('student', 'admission_year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('student', 'fname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('student', 'gender',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('student', 'level',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 'p_mobile1',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 'p_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('student', 'parent_id',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('student', 's_type',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('student', 'sname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('student', 's_type',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('student', 'parent_id',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('student', 'p_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('student', 'p_mobile1',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('student', 'level',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('student', 'gender',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('student', 'fname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('student', 'admission_year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('student', 'activity_group',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('receipt', 'update_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('receipt', 'tran_desc',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('receipt', 'insert_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('receipt', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('receipt', 'amount',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('billing', 'update_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('billing', 'insert_user',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('billing', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
