"""empty message

Revision ID: a80ab7ca5e1a
Revises: d77560220b0d
Create Date: 2020-01-25 06:13:50.820538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a80ab7ca5e1a'
down_revision = 'd77560220b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_calendar', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('academic_calendar', 'is_current')
    op.add_column('billing', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('billing', 'is_current')
    op.add_column('fee_schedule', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('fee_schedule', 'is_current')
    op.add_column('fee_schedule_detail', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('fee_schedule_detail', 'is_current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_schedule_detail', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('fee_schedule_detail', 'is_active')
    op.add_column('fee_schedule', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('fee_schedule', 'is_active')
    op.add_column('billing', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('billing', 'is_active')
    op.add_column('academic_calendar', sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('academic_calendar', 'is_active')
    # ### end Alembic commands ###
