"""empty message

Revision ID: aeef088e8ec6
Revises: 1165e453879a
Create Date: 2020-01-23 23:24:26.268588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeef088e8ec6'
down_revision = '1165e453879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_academic_calendar_insert_date'), 'academic_calendar', ['insert_date'], unique=False)
    op.create_index(op.f('ix_academic_calendar_update_date'), 'academic_calendar', ['update_date'], unique=False)
    op.create_index(op.f('ix_billing_insert_date'), 'billing', ['insert_date'], unique=False)
    op.create_index(op.f('ix_billing_update_date'), 'billing', ['update_date'], unique=False)
    op.create_index(op.f('ix_fee_schedule_detail_insert_date'), 'fee_schedule_detail', ['insert_date'], unique=False)
    op.create_index(op.f('ix_fee_schedule_detail_update_date'), 'fee_schedule_detail', ['update_date'], unique=False)
    op.create_index(op.f('ix_receipt_insert_date'), 'receipt', ['insert_date'], unique=False)
    op.create_index(op.f('ix_receipt_update_date'), 'receipt', ['update_date'], unique=False)
    op.create_index(op.f('ix_student_insert_date'), 'student', ['insert_date'], unique=False)
    op.create_index(op.f('ix_student_update_date'), 'student', ['update_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_update_date'), table_name='student')
    op.drop_index(op.f('ix_student_insert_date'), table_name='student')
    op.drop_index(op.f('ix_receipt_update_date'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_insert_date'), table_name='receipt')
    op.drop_index(op.f('ix_fee_schedule_detail_update_date'), table_name='fee_schedule_detail')
    op.drop_index(op.f('ix_fee_schedule_detail_insert_date'), table_name='fee_schedule_detail')
    op.drop_index(op.f('ix_billing_update_date'), table_name='billing')
    op.drop_index(op.f('ix_billing_insert_date'), table_name='billing')
    op.drop_index(op.f('ix_academic_calendar_update_date'), table_name='academic_calendar')
    op.drop_index(op.f('ix_academic_calendar_insert_date'), table_name='academic_calendar')
    # ### end Alembic commands ###
