"""empty message

Revision ID: bcea2dc55eb6
Revises: 190725c3a381
Create Date: 2020-01-24 07:06:14.976761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcea2dc55eb6'
down_revision = '190725c3a381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_type', sa.String(length=10), nullable=False))
    op.drop_column('student', 's_stype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_stype', mysql.VARCHAR(length=2), nullable=True))
    op.drop_column('student', 's_type')
    # ### end Alembic commands ###
