"""empty message

Revision ID: d77560220b0d
Revises: 1082a9510869
Create Date: 2020-01-24 08:49:00.452809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd77560220b0d'
down_revision = '1082a9510869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billing_ibfk_2', 'billing', type_='foreignkey')
    op.drop_column('billing', 'student_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('student_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('billing_ibfk_2', 'billing', 'student_category', ['student_category_id'], ['id'])
    # ### end Alembic commands ###
