"""model update

Revision ID: ecac02e05b22
Revises: 8cb792d0c2da
Create Date: 2020-01-24 00:32:39.093130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecac02e05b22'
down_revision = '8cb792d0c2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee_schedule_detail', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee_schedule_detail', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
